/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AdminPanel": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "ApiBackend": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "DocsRenderer": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "FrontCatalog": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "SpecsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}